export const floor1 = {
  top: [
    {
      x_location: 2,
      y_location: 'C',
      Layer: 2,
      direction: 'riht',
      status: 'new',
    },
    {
      x_location: 2,
      y_location: 'G',
      Layer: 1,
      direction: 'left',
      status: 'in proggress',
    },
    {
      x_location: 3,
      y_location: 'A',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
    {
      x_location: 5,
      y_location: 'A',
      Layer: 2,
      direction: 'both',
      status: 'completed',
    },
    {
      x_location: 5,
      y_location: 'F',
      Layer: 3,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 7,
      y_location: 'E',
      Layer: 4,
      direction: 'right',
      status: 'new',
    },
    {
      x_location: 9,
      y_location: 'D',
      Layer: 1,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 12,
      y_location: 'A',
      Layer: 2,
      direction: 'lect',
      status: 'new',
    },
    {
      x_location: 13,
      y_location: 'C',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
  ],
  middle: [
    {
      x_location: 2,
      y_location: 'C',
      Layer: 2,
      direction: 'riht',
      status: 'new',
    },
    {
      x_location: 2,
      y_location: 'G',
      Layer: 1,
      direction: 'left',
      status: 'in proggress',
    },
    {
      x_location: 3,
      y_location: 'A',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
    {
      x_location: 5,
      y_location: 'A',
      Layer: 2,
      direction: 'both',
      status: 'completed',
    },
    {
      x_location: 5,
      y_location: 'F',
      Layer: 3,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 7,
      y_location: 'E',
      Layer: 4,
      direction: 'right',
      status: 'new',
    },
    {
      x_location: 9,
      y_location: 'D',
      Layer: 1,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 12,
      y_location: 'A',
      Layer: 2,
      direction: 'lect',
      status: 'new',
    },
    {
      x_location: 13,
      y_location: 'C',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
  ],
  bottom: [
    {
      x_location: 2,
      y_location: 'C',
      Layer: 2,
      direction: 'riht',
      status: 'new',
    },
    {
      x_location: 2,
      y_location: 'G',
      Layer: 1,
      direction: 'left',
      status: 'in proggress',
    },
    {
      x_location: 3,
      y_location: 'A',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
    {
      x_location: 5,
      y_location: 'A',
      Layer: 2,
      direction: 'both',
      status: 'completed',
    },
    {
      x_location: 5,
      y_location: 'F',
      Layer: 3,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 7,
      y_location: 'E',
      Layer: 4,
      direction: 'right',
      status: 'new',
    },
    {
      x_location: 9,
      y_location: 'D',
      Layer: 1,
      direction: 'left',
      status: 'completed',
    },
    {
      x_location: 12,
      y_location: 'A',
      Layer: 2,
      direction: 'lect',
      status: 'new',
    },
    {
      x_location: 13,
      y_location: 'C',
      Layer: 1,
      direction: 'both',
      status: 'in proggress',
    },
  ],
  site_plan: [],
};

export const Project1 = {
  Horizontal: {
    Raft: {},
    'Single Element': {},
    Celling: {},
    Beam: {},
  },
  vertical: {
    //Shlurry Wall, Piles, Wall, Column
    'Shlurry Wall': {},
    Piles: {},
    Wall: {},
    Column: {},
  },
};
